// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PredictClient is the client API for Predict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictClient interface {
	GetPredict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
}

type predictClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictClient(cc grpc.ClientConnInterface) PredictClient {
	return &predictClient{cc}
}

func (c *predictClient) GetPredict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, "/service.Predict/getPredict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictServer is the server API for Predict service.
// All implementations must embed UnimplementedPredictServer
// for forward compatibility
type PredictServer interface {
	GetPredict(context.Context, *PredictRequest) (*PredictReply, error)
	mustEmbedUnimplementedPredictServer()
}

// UnimplementedPredictServer must be embedded to have forward compatible implementations.
type UnimplementedPredictServer struct {
}

func (UnimplementedPredictServer) GetPredict(context.Context, *PredictRequest) (*PredictReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredict not implemented")
}
func (UnimplementedPredictServer) mustEmbedUnimplementedPredictServer() {}

// UnsafePredictServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictServer will
// result in compilation errors.
type UnsafePredictServer interface {
	mustEmbedUnimplementedPredictServer()
}

func RegisterPredictServer(s grpc.ServiceRegistrar, srv PredictServer) {
	s.RegisterService(&Predict_ServiceDesc, srv)
}

func _Predict_GetPredict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).GetPredict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Predict/getPredict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).GetPredict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Predict_ServiceDesc is the grpc.ServiceDesc for Predict service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Predict_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Predict",
	HandlerType: (*PredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPredict",
			Handler:    _Predict_GetPredict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "IoProject.proto",
}
